version: '3'

networks:
  yii:
    name: yii

services:
  nginx:
    container_name: yii_nginx
    image: nginx:latest
    ports:
      - 2000:80
    volumes:
      - ./www:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - yii
    depends_on:
      - php

  php:
    container_name: yii_php
    build: ./images/php81fpm
    volumes:
      - ./www:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - yii
    depends_on:
      - postgresql
    environment:
      - DATABASE_URL=pgsql://yii:yii@postgresql/yii

  postgresql:
    container_name: yii_postgresql
    image: postgres:latest
    volumes:
      - ./www:/var/www
      - ./postgresql-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=yii
      - POSTGRES_PASSWORD=yii
      - POSTGRES_DB=yii
    networks:
      - yii

  adminer:
    container_name: yii_adminer
    image: adminer:latest
    ports:
      - 2001:8080
    networks:
      - yii
    depends_on:
      - postgresql
    environment:
      - ADMINER_DEFAULT_SERVER=postgresql