version: '3'

networks:
  yii:
    name: yii

services:
  nginx:
    container_name: yii_nginx
    image: nginx:latest
    ports:
      - 2000:80
    volumes:
      - ./www:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - yii
    depends_on:
      - php

  php:
    container_name: yii_php
    build: ./images/php81fpm
    volumes:
      - ./www:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - yii
    environment:
      - DATABASE_URL=pgsql://yii:yii@postgresql/yii
